### ISSUE TITLE
github action support

### ISSUE THREAD

**Issue by Ran-Xing** [libgdx/packr#214]
```yaml
      - 
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
        with:
          json: test.json
          jdk: 16
          platform: mac
          executable: test
          mainclass: core.ui.MainActivity
          classpath: test.jar
          vmargs: |
            "Dfile.encoding=utf-8",
            "ParallelGCThreads=4 ", 
            "AggressiveHeap", 
            "+UseParallelGC", 
            "Xms512M",
            "Xmx1024M"
          output: test.app
          icon: test.icns
```
Hope to support
